platform :ios, '12.0'

target 'xkcd-viewer' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for xkcd-viewer
  pod 'TinyConstraints'

  target 'xkcd-viewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
